version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: quarkus_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'quarkus'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: